// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsGVmC4Dd-ErzxkUbTxPzLANDuITM0EQU',
    appId: '1:144930633639:web:df946920e2663d54426882',
    messagingSenderId: '144930633639',
    projectId: 'medic-app-e1834',
    authDomain: 'medic-app-e1834.firebaseapp.com',
    storageBucket: 'medic-app-e1834.firebasestorage.app',
    measurementId: 'G-EZ2KZVS68C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfEvykCNPzJeJAX-aSQcKNh0HeQNRL6bA',
    appId: '1:144930633639:android:2d050efcd58add1d426882',
    messagingSenderId: '144930633639',
    projectId: 'medic-app-e1834',
    storageBucket: 'medic-app-e1834.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpbgc5_qRHDgtNWkdCHVsRruwz9yCDFqw',
    appId: '1:144930633639:ios:d60e2e0cd181a503426882',
    messagingSenderId: '144930633639',
    projectId: 'medic-app-e1834',
    storageBucket: 'medic-app-e1834.firebasestorage.app',
    iosBundleId: 'com.example.medicapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpbgc5_qRHDgtNWkdCHVsRruwz9yCDFqw',
    appId: '1:144930633639:ios:d60e2e0cd181a503426882',
    messagingSenderId: '144930633639',
    projectId: 'medic-app-e1834',
    storageBucket: 'medic-app-e1834.firebasestorage.app',
    iosBundleId: 'com.example.medicapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsGVmC4Dd-ErzxkUbTxPzLANDuITM0EQU',
    appId: '1:144930633639:web:e124e46abd8031f5426882',
    messagingSenderId: '144930633639',
    projectId: 'medic-app-e1834',
    authDomain: 'medic-app-e1834.firebaseapp.com',
    storageBucket: 'medic-app-e1834.firebasestorage.app',
    measurementId: 'G-W5LZTDQLJG',
  );
}
